# Generated by Django 5.1 on 2024-09-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='worry_dialog_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
