# Generated by Django 5.1 on 2024-09-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_userdata_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="places_information",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
