# Generated by Django 5.1 on 2024-09-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userdata_places_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='website_url',
        ),
        migrations.AddField(
            model_name='userdata',
            name='website_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
