# Generated by Django 5.1 on 2024-09-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_customerreviewinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="place_id_from_review",
            field=models.CharField(default="", max_length=255),
        ),
    ]
