# Generated by Django 5.1 on 2024-09-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_customerreviewinfo_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='company_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='company_website_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
