# Generated by Django 5.1 on 2024-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_userdata_company_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='worry_rating',
            field=models.IntegerField(default=4),
        ),
    ]
