# Generated by Django 5.1 on 2024-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_alter_userdata_worry_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="posted_with_bubble_rating_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdata",
            name="bubble_rating_platform",
            field=models.BooleanField(default=False),
        ),
    ]
