# Generated by Django 5.1 on 2024-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_customerreviewinfo_posted_with_bubble_rating_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='in_location_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
