# Generated by Django 5.1 on 2024-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_userdata_in_location_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="posted_with_in_store_mode",
            field=models.BooleanField(default=False),
        ),
    ]
