# Generated by Django 5.1 on 2024-09-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_reviewstopostlater_customerreviewinfo_review_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="posted_to_google_after_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
