# Generated by Django 5.1 on 2024-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_alter_reviewstopostlater_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="pending_google_review",
            field=models.BooleanField(default=False),
        ),
    ]
