# Generated by Django 5.1 on 2024-09-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_customerreviewinfo_pending_google_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewstopostlater",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reviewstopostlater",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="bubble_rating_platform",
            field=models.BooleanField(default=True),
        ),
    ]
