# Generated by Django 5.1 on 2024-09-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0024_reviewstopostlater_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="email_delay",
            field=models.IntegerField(default=60),
        ),
    ]
