# Generated by Django 5.1 on 2024-09-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_reviewstopostlater_tone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="categories",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
