# Generated by Django 5.1 on 2024-09-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0027_userdata_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="text_sent_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
