# Generated by Django 5.1 on 2024-09-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0028_customerreviewinfo_text_sent_for_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewstopostlater",
            name="badges",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
