# Generated by Django 5.1.1 on 2024-10-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0030_scheduledjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(default="google-business", max_length=100),
        ),
    ]
