# Generated by Django 5.1.1 on 2024-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0031_customuser_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="card_description",
            field=models.TextField(blank=True, default="How did we do? 🤔"),
        ),
    ]
