# Generated by Django 5.1.1 on 2024-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0032_userdata_card_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="card_description",
            field=models.CharField(blank=True, default="How did we do? 🤔"),
        ),
    ]
