# Generated by Django 5.1.1 on 2024-10-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0033_alter_userdata_card_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="questions",
        ),
    ]
