# Generated by Django 5.1.1 on 2024-10-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0034_remove_userdata_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_subscription",
            field=models.CharField(default="free-trial", max_length=100),
        ),
    ]
