# Generated by Django 5.1.1 on 2024-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0036_customeruser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="user_score",
            field=models.FloatField(default=0.0),
        ),
    ]
