# Generated by Django 5.1.1 on 2024-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0037_alter_customeruser_user_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="places_reviewed",
            field=models.JSONField(default=list),
        ),
    ]
