# Generated by Django 5.1.1 on 2024-10-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0041_customerreviewinfo_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreviewinfo",
            name="score_received",
            field=models.FloatField(default=0.0),
        ),
    ]
