# Generated by Django 5.1.1 on 2024-10-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0042_customerreviewinfo_score_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="avatar_svg",
            field=models.TextField(default=""),
        ),
    ]
