# Generated by Django 5.1.1 on 2024-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_customeruser_avatar_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="chosen_icon",
            field=models.CharField(blank=True, default="Star"),
        ),
    ]
