# Generated by Django 5.1.1 on 2024-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_userdata_chosen_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="custom_website_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
