# Generated by Django 5.1.1 on 2024-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0045_userdata_custom_website_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="customer_website_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
