# Generated by Django 5.1.1 on 2024-11-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_websitedetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinearLikeTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.TextField(blank=True, null=True)),
                ("generated_tasks", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
